---
#################################
############# Debian, Ubuntu, ...
- name: Install Mysql package
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - libmariadb-client-lgpl-dev
    - python-mysqldb
    - python3-mysqldb

- name: Create mysql_config symlink
  file:
    src: "/usr/bin/mariadb_config"
    dest: "/usr/bin/mysql_config"
    state: link

- name: Update MySQL root password for all root accounts
  mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ db_root_password }}"
      login_user: root
      login_password: "{{ db_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Start Mysql Service
  service: name=mysql state=started enabled=true
